# Generated by Django 4.1.7 on 2023-03-11 18:09

from django.db import migrations, models

from cidades.constants import cities


def create_locations(apps, schema_editor):
    Location = apps.get_model("cidades", "Location")

    objs = [
        Location(
            id=c["code"], verbose=c["verbose_name"], name=c["name"], state=c["state"]
        )
        for c in cities.data
    ]

    Location.objects.bulk_create(objs)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='id')),
                ('verbose', models.CharField(max_length=255, verbose_name='verbose')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('state', models.CharField(max_length=255, verbose_name='state')),
            ],
        ),
        migrations.RunPython(create_locations)
    ]
